### ISSUE TITLE
Implementation of BooleanArrayParameter

### ISSUE THREAD

**Issue by phrb** [dose78/FRPA#1]
Hi, I am also using OpenTuner in my work to tune [SAT solver combinations](https://github.com/phrb/sat-opentuner), and I want to implement an IntegerParameterArray. It's not supported by OpenTuner at this moment, and I saw you're using a BooleanArrayParameter, which is also not implemented.

How did you implement it? I searched for your implementation, but I can't find it. Could you explain it to me, or link the implementation somewhere?

Thanks!

**Comment by dose78** [comment]
Hello,

It seems that `BooleanArrayParameter` was renamed to `BooleanParameterArray` in [this commit](https://github.com/jansel/opentuner/commit/b9004babcd8a0ca45e9691df2fe43597f5d8175d#diff-1389484f4d0a3af9e6e1c22b315668e0L1140). Despite the TODOs, I think `BooleanParameterArray` is implemented. OpenTuner parameters sometimes implement methods so that particular tuning strategies can manipulate them in efficient ways, beyond just presenting a list of values. I think we're seeing methods for a particular strategy that haven't been implemented, but the parameters should be functionally correct regardless.

**Comment by phrb** [comment]
Thanks!

I imported `IntegerParameterArray` from `manipulator.py` and it worked. The new tuner was able to find better solutions, in comparison with the 100 `IntegerParameter` tuner I was using before. Did you implement `op3_swarm` and `op3_cross` for `BooleanParameterArray`?

Which techniques did you use when tuning? Did you implement any new ones?

**Comment by dose78** [comment]
I don't recall implementing `op3_swarm` or `op3_cross`. If `BooleanParameterArray` doesn't work now, it is possible that it worked at the time I wrote the code. I didn't implement any new techniques.

**Comment by phrb** [comment]
Thanks, you were very helpful!

**Comment by deliahu** [comment]
My pleasure!
